# Generated by Django 5.1.7 on 2025-05-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_descricao_editora_nome_remove_livro_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autores',
            field=models.ManyToManyField(blank=True, related_name='livros', to='core.autor'),
        ),
    ]
