# Generated by Django 5.2.3 on 2025-06-27 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_livro_autores'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['descricao'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['descricao'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='editora',
            options={'ordering': ['nome'], 'verbose_name': 'Editora', 'verbose_name_plural': 'Editoras'},
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['titulo'], 'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.image'),
        ),
        migrations.AddIndex(
            model_name='autor',
            index=models.Index(fields=['descricao'], name='core_autor_descric_5f18f4_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['descricao'], name='core_catego_descric_a1eca8_idx'),
        ),
        migrations.AddIndex(
            model_name='editora',
            index=models.Index(fields=['nome'], name='core_editor_nome_36bdcf_idx'),
        ),
        migrations.AddIndex(
            model_name='editora',
            index=models.Index(fields=['site'], name='core_editor_site_217b1b_idx'),
        ),
        migrations.AddIndex(
            model_name='livro',
            index=models.Index(fields=['titulo'], name='core_livro_titulo_b36e60_idx'),
        ),
        migrations.AddIndex(
            model_name='livro',
            index=models.Index(fields=['isbn'], name='core_livro_isbn_f85fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='livro',
            index=models.Index(fields=['quantidade'], name='core_livro_quantid_a9d217_idx'),
        ),
        migrations.AddIndex(
            model_name='livro',
            index=models.Index(fields=['preco'], name='core_livro_preco_afeab5_idx'),
        ),
    ]
