# Generated by Django 5.2.3 on 2025-06-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_editora_cidade_editora_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='nome',
            field=models.CharField(default='Sem Nome', max_length=100),
            preserve_default=False,
        ),
    ]
